# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
markdown_extensions:
  - attr_list